server:
  port: 8080
  servlet:
    encoding:
      force: true
      force-request: true
      force-response: true
      charset: utf-8
    context-path: /orm
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orm
    username: root
    password: "020910"
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:xml/*Mapper.xml

